[package]

name = "declarative-dataflow"
version = "0.1.0"
authors = ["Nikolas Göbel <me@nikolasgoebel.com>", "Frank McSherry <fmcsherry@me.com>"]
edition = "2018"

description = "A reactive query engine built on Differential Dataflow."

repository = "https://github.com/comnik/declarative-dataflow.git"
keywords = ["differential", "dataflow",  "datalog", "graphql", "query"]
license = "MIT"

[dependencies]
jemallocator = "0.1.8"
timely = { git = "https://github.com/TimelyDataflow/timely-dataflow", features = ["bincode"] }
differential-dataflow = { git = "https://github.com/TimelyDataflow/differential-dataflow" }
abomonation = "0.7"
abomonation_derive = "0.3"
serde = "1"
serde_derive = "1"
serde_json = "1"
mio = "0.6.16"
slab = "0.4.1"
ws = { git = "https://github.com/comnik/ws-rs" }
log = "0.4"
env_logger = "0.5.6"
getopts = "0.2.18"
num-rational = { version = "0.2", features = ["std", "serde"] }
timely_sort = "0.1.6"
graphql-parser = { version = "0.2.2", optional = true }
csv = { version = "1", optional = true }
chrono = { version = "0.4", optional = true }

[features]
set-semantics = []
uuids = []
graphql = ["graphql-parser"]
csv-source = ["csv", "chrono"]

[[bin]]
name = "server"

[profile.release]
opt-level = 3
debug = true
debug-assertions = false
rpath = false
lto = false
codegen-units = 4
